### ISSUE TITLE
EmaSimpleSkin.gltf is not displayed

### ISSUE THREAD

**Issue by cx20** [pissang/qtek-model-viewer#12]
I tried to display the following model in QMV.js.
https://github.com/cx20/jsdo-static-contents/tree/master/models/gltf/2.0/EmaSimpleSkin_blender/glTF
![emasimpleskin](https://user-images.githubusercontent.com/1833979/33486329-fae48ae8-d6ec-11e7-9dd2-9f73db07b4f5.gif)

However, it does not appear to be displayed.
http://jsdo.it/cx20/SpgU

I tried with each browser, the following warning was displayed on the console.

Chrome:
```js
GL ERROR :GL_INVALID_OPERATION : glDrawElements: range out of bounds for buffer
```
Firefox:
```js
QMV.js:14017:21
WebGL warning: drawElements: Bound element array buffer is too small for given count and offset.
```

**Comment by pissang** [comment]
Thanks again for the case report. Never thought the indices can be `ubyte` format. It's usually `ushort`. Fixed in https://github.com/pissang/qtek/commit/0493899de6a4887444e6d1a00f866cd3a7ee95ef

![machi 2017-12-02 01-04-35](https://user-images.githubusercontent.com/841551/33494120-26341c3a-d6fd-11e7-820e-26eeda1dd1c7.jpg)

**Comment by cx20** [comment]
I confirmed that it will be displayed in the latest version.
http://jsdo.it/cx20/SpgU
![image](https://user-images.githubusercontent.com/1833979/33512523-922a33b6-d775-11e7-9933-9874b76d7531.png)
