### ISSUE TITLE
Polly.gltf floor and nameplate are not displayed

### ISSUE THREAD

**Issue by cx20** [pissang/qtek-model-viewer#13]
I tried displaying Polly.gltf.
https://github.com/KhronosGroup/glTF-Blender-Exporter/tree/master/polly

However, QTEK seems that floor and nameplate are not displayed.

QMV.js + Polly.gltf result: http://jsdo.it/cx20/S8kv
![image](https://user-images.githubusercontent.com/1833979/33496057-2271a2d4-d70c-11e7-9260-2228be749d3e.png)

Three.js + Polly.gtf result: http://jsdo.it/cx20/qugw
![image](https://user-images.githubusercontent.com/1833979/33496108-45c5cf12-d70c-11e7-9aa3-f9df07273e6a.png)

**Comment by pissang** [comment]
It seems the same problem with https://github.com/pissang/qtek-model-viewer/issues/12

Fixed in https://github.com/pissang/qtek/commit/0493899de6a4887444e6d1a00f866cd3a7ee95ef

![screen shot 2017-12-02 at 10 31 16 am](https://user-images.githubusercontent.com/841551/33510837-7de2f34e-d74c-11e7-9c08-e37c0835d5f5.jpg)

**Comment by cx20** [comment]
I confirmed that there is no problem with the latest version. Thanks!
http://jsdo.it/cx20/S8kv
![image](https://user-images.githubusercontent.com/1833979/33512558-090d8eb0-d776-11e7-8100-d122af46779c.png)
