### ISSUE TITLE
Unable to build QMV.js

### ISSUE THREAD

**Issue by cx20** [pissang/qtek-model-viewer#3]
I tried the following command.
```bat
npm install
npm run build
```
However, an error occurred.
```bat
C:\home\edu\javascript\library\qtek-model-viewer-master>npm run build

> qtek-model-viewer@0.1.0 build C:\home\edu\javascript\library\qtek-model-viewer-master
> npm run glsl2js && rollup -c && uglifyjs -c -m -- dist/QMV.js > dist/QMV.min.js


> qtek-model-viewer@0.1.0 glsl2js C:\home\edu\javascript\library\qtek-model-viewer-master
> node build/glsl2js.js


C:\home\edu\javascript\library\qtek-model-viewer-master/index.js → dist/QMV.js...
[!] Error: 'default' is not exported by node_modules\zrender\lib\core\util.js
https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
src\Viewer.js (23:7)
21: import SceneHelper from './graphic/SceneHelper';
22: import defaultSceneConfig from './defaultSceneConfig';
23: import zrUtil from 'zrender/lib/core/util';
           ^
24:
25: import getBoundingBoxWithSkinning from './util/getBoundingBoxWithSkinning';
```

The environment used for the build is the Windows 10 command prompt.
I also tried Bash on Windows, but the result was an error similar to the previous one.

How can I create the latest version of QMV.js?

**Comment by pissang** [comment]
It's because one of the dependencies [zrender](https://github.com/ecomfe/zrender) just changed from CommonJS modules to ES6 modules in the latest version. Already fixed in https://github.com/pissang/qtek-model-viewer/commit/8fdee5be90846577a89965ff18576118c8095e26

BTW if you want to build the code by yourself, it is suggested that clone the latest code of [qtek](https://github.com/pissang/qtek) and put it under the `node_modules`.

**Comment by cx20** [comment]
@pissang I built it according to your advice and it worked. Thanks!
