### ISSUE TITLE
TextureSettingsTest model does not display correctly 

### ISSUE THREAD

**Issue by cx20** [pissang/qtek-model-viewer#4]
I tried to display the following model.
However, the result of the QMV.js is incorrect.
https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/TextureSettingsTest

[QMV.js + TextureSettingsTest.gltf result:](https://cx20.github.io/gltf-test/examples/qtek/index.html?category=tutorialModels&model=TextureSettingsTest&scale=0.2&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/32607737-42788640-c59d-11e7-8690-44bbbd6fd51f.png)

It is desirable to have the following results.
![image](https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/TextureSettingsTest/screenshot/screenshot.png?raw=true)

**Comment by pissang** [comment]
Fixed in https://github.com/pissang/qtek-model-viewer/commit/638d439e12337061c03a865277e3c5b4b6c04702. [qtek](https://github.com/pissang/qtek/commit/5d82e50f1f0485ed94ece5ca8dd8f29d8554f027) also needs to be updated, here is the result.

<img width="275" alt="screen shot 2017-11-09 at 10 18 40 pm" src="https://user-images.githubusercontent.com/841551/32609927-358bbd22-c59c-11e7-93c1-313a1e4783ef.png">

Didn't notice that you are working on the `gltf-tests` project. Really thanks for the detailed test. Will have a look at other failed cases. And morph animation haven't been implemented yet.

**Comment by pissang** [comment]
Also fixed the display of `Triangles`, `Triangle Without Indices`,  `Animated Triangle`, `Simple Meshes`. Which extent is 0 on the z axis.

**Comment by cx20** [comment]
@pissang I updated the status of gltf-test.
https://github.com/cx20/gltf-test
Since TextureSettingsTest has been fixed, this Issue is closed.

**Comment by pissang** [comment]
@cx20 Thanks again!
