### ISSUE TITLE
Suzanne.gltf is displayed dark

### ISSUE THREAD

**Issue by cx20** [pissang/qtek-model-viewer#7]
I tried to display the following model.
https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Suzanne

However, it appears to be quite dark.

[QMV.js + Suzanne.gltf result:](https://cx20.github.io/gltf-test/examples/qtek/index.html?category=tutorialModels&model=Suzanne&scale=1&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/32662959-a0c9be44-c66f-11e7-8d3e-7e13908ed712.png)

I tried setting the light intensity to 10 times, and it got a little brighter. 
```js
    viewer.setMainLight({
        intensity: 1*10,
        color: '#fff',
        alpha: 45,
        beta: 45
    });
    viewer.setAmbientLight({
        intensity: 0.8*10
    });
```
However, things like molds are now displayed.

![image](https://user-images.githubusercontent.com/1833979/32662917-7af5c2d0-c66f-11e7-98cd-9cea48885293.png)

Perhaps the usage of the light may be incorrect. In that case, please tell me how to set it.

**Comment by pissang** [comment]
I think it works as expected. 

The material of Suzanne is gloss metal. Which have no diffuse reflection, only specular reflection. So ambient light, which only contributes the diffuse part, have no effects at all. No matter what the intensity is. Directional light also can only contribute a little spot since the surface is gloss.

For gloss metal material like this. The best way is to use image based lighting. In QMV.js `addAmbientCubeMap({ texture: 'someHdrTexture.hdr' })` is for adding the IBL.

You can also have a try on the online viewer http://pissang.github.io/qtek-model-viewer/editor

**Comment by cx20** [comment]
I confirmed that Suzanne.gltf will be displayed by using setAmbientCubemapLight instead of setAmbientLight.

```js
/*
    // Set ambient light options
    viewer.setAmbientLight({
        // Ambient light intensity
        intensity: 0.8
    });
*/
    // Set ambient cubemap light options
    viewer.setAmbientCubemapLight({
        // Ambient cubemap light intensity
        intensity: 0.8,
        // Ambient Cubemap Texture
        texture: '../../textures/hdr/pisa.hdr'
    });
```

![image](https://user-images.githubusercontent.com/1833979/32681459-f3366734-c6b2-11e7-9c09-15b0afb3ac58.png)

However, in that case, it seems that Triangle.gltf is black and nothing is displayed.
https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Triangle

I want to display all the samples with the same light setting, is it difficult?
In other libraries (Three.js) etc., all samples are displayed with the same light setting.
https://github.com/cx20/gltf-test

**Comment by pissang** [comment]
The triangle glTF is black because it has no surface normals. In https://github.com/pissang/qtek/commit/78d20e20c4a49da9964f30ad3e26e688035eeae9 I add normal generation if mesh don't have.

Simple models and more complex models can have one light setting. And PBR models further  PBR models needs extra ambientCubeMap for Image Based Lighting, which I believe other libraries also need to add.

**Comment by cx20** [comment]
@pissang Thank you for support of normal generation. However, there seems to be a problem with this correspondence.
When calling generateVertexNormals, Triangle.gltf will not get an error, but it seems that TriangleWithoutIndices.gltf got an error.

```js
QMV.js:17705 
Uncaught TypeError: Cannot read property 'length' of null
    at sub.generateVertexNormals (QMV.js:17705)
    at sub.<anonymous> (QMV.js:18962)
    at Array.forEach (<anonymous>)
    at Object.each (QMV.js:442)
    at sub._parseMeshes (QMV.js:18865)
    at afterLoadBuffer (QMV.js:18381)
    at checkLoad (QMV.js:18326)
    at QMV.js:18342
    at Object.onload (QMV.js:18446)
    at XMLHttpRequest.xhr.onload (QMV.js:11376)
```
```js
        for (var f = 0; f < indices.length;) {
                                    ^^^^^^
```

Sorry if it seems to be a known problem.

**Comment by pissang** [comment]
My fault. Didn't handle the case without indices. Actually I just see it's still in the TODO list. Will fix that then. Thanks again!

**Comment by pissang** [comment]
@cx20 I think it's ok now:)

**Comment by cx20** [comment]
@pissang I confirmed that TriangleWithoutIndices.gltf will be displayed as well. I would like to close this Issue.
